In [33]:
import torch

In [34]:
x = torch.zeros(10)
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
x.size()

torch.Size([10])

In [36]:
x+2

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [37]:
y = torch.zeros(10,10)
y

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
x+3* torch.eye(10)

tensor([[3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 3., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 3., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 3., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 3.]])

In [39]:
x = x.unsqueeze(0)

In [40]:
x.size()

torch.Size([1, 10])

In [41]:
x = x.unsqueeze(2)

In [42]:
x.size()

torch.Size([1, 10, 1])

In [43]:
x = x.squeeze(2)
x.size()

torch.Size([1, 10])

In [44]:
x = x.squeeze(0)
x.size()

torch.Size([10])

In [45]:
x.squeeze_(0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])